language: java

# https://docs.travis-ci.com/user/languages/java/#Caching

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.groovy/grapes/

jdk: openjdk8
install: true  # Overwrite default install step (./gradlew assemble)

jobs:
  include:
    - stage: spotless
      script: ./gradlew spotlessCheck
    - stage: build
      script: ./gradlew jar # TODO: Build jar only once
    - stage: test
      script: ./gradlew jar test
    - stage: deploy
      script:
        - |
          if [ "$TRAVIS_BRANCH" == "master" ]; then
            ./gradlew jar bintrayUpload -DbintrayUser=$BINTRAY_USER -DbintrayApiKey=$BINTRAY_API_KEY
          elif [ "$TRAVIS_BRANCH" == "develop" ]; then
            ./gradlew jar bintrayUpload -DbintrayUser=$BINTRAY_USER -DbintrayApiKey=$BINTRAY_API_KEY -Pversion=snapshot
          fi
